server.port=8086

# Logging
logging.level.root=INFO
logging.level.com.ratelimiter=INFO

# Spring Data Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.timeout=3000ms

# OpenAPI / Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Rate Limiter Default Settings
app.rate-limiter.capacity=10
app.rate-limiter.refill-rate=2
