server.port=8085

# Logging
logging.level.root=INFO
logging.level.com.consistenthashing=INFO

# OpenAPI / Swagger configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Consistent Hashing configuration
app.nodes=localhost:27017,localhost:27018,localhost:27019
app.virtual-nodes=150
app.mongo4.host=localhost
app.mongo4.port=27020
