server.port=8087

# Logging
logging.level.root=INFO
logging.level.com.autocomplete=INFO

# Spring Data Redis Configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6380}
spring.data.redis.timeout=3000ms

# OpenAPI / Swagger UI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Autocomplete Configuration
app.autocomplete.default-k=5
app.autocomplete.cache-ttl-minutes=10
